syntax = "proto3";

option go_package = "./;protos";
package roadbook;
import "file.proto";

message RoadbookWaypointNavigation {
  double distance = 1;
  double duration = 2;
  string travelMode = 3;
  // 导航数据下载地址
  file.Urls urls = 4;
}

message RoadbookWaypointItem {
  string id = 1;

  message Coords {
    double latitude = 1;
    double longitude = 2;
  }
  Coords coords = 2;

  // 完整名，country·state·region·city·town，五级
  message City {
    string country = 1;
    string state = 2;
    string region = 3;
    string city = 4;
    string town = 5;
    string road = 6;
  }
  City city = 3;
  string address = 4;
  string icon = 5;
  // 上一个点前往此点的导航数据
  RoadbookWaypointNavigation navigation = 6;
  int64 lastNavigationTime = 7;
}

message RoadbookTimelineItem {
  string id = 1;
  string title = 2;
  string desc = 3;
  int32 days = 4;
  repeated RoadbookWaypointItem waypoints = 5;
}

message RoadbookPermissions {
  // 路人也可以看
  bool allowShare = 1;
}

message RoadbookItem {
  string id = 1;
  string title = 2;
  string desc = 3;
  int64 startTime = 4;

  repeated RoadbookTimelineItem timelines = 5;

  RoadbookPermissions permissions = 6;

  string authorId = 7;

  // 1、-1
  int32 status = 8;
  int64 createTime = 9;
  int64 lastUpdateTime = 10;
  int64 deleteTime = 11;
}

message AddRoadbook {
  message Request {
    string title = 1;
    string desc = 2;
    int64 startTime = 3;
  }
  message Response { RoadbookItem roadbook = 1; }
}

message GetRoadbookList {
  message Request {
    // 可选
    repeated string ids = 1;
    int32 pageNum = 2;
    int32 pageSize = 3;
  }
  message Response {
    repeated RoadbookItem list = 1;
    int32 total = 2;
  }
}

message GetRoadbookDetail {
  message Request { string id = 1; }
  message Response { RoadbookItem roadbook = 1; }
}

message UpdateRoadbook {
  message Request {
    string id = 1;
    string title = 2;
    string desc = 3;
    int64 startTime = 4;

    repeated RoadbookTimelineItem timelines = 5;

    RoadbookPermissions permissions = 6;
  }
  message Response {}
}

message DeleteRoadbook {
  message Request { string id = 1; }
  message Response {}
}

message AddRoadbookTimeline {
  message Request {
    string id = 1;
    string title = 2;
    string desc = 3;
  }
  message Response { RoadbookTimelineItem roadbookTimelineItem = 1; }
}