syntax = "proto3";

option go_package = "./;protos";
package road;

message RoadName {
  string en = 1;
  string zhHans = 2;
  string zhHant = 3;
}

message RoadInfo {
  // "motorway" | "trunk" | "primary" | "secondary" | "tertiary" |
  // "unclassified"
  string type = 1;
  string code = 2;
  RoadName name = 3;
  // map<string, string> names = 4;
  string shortCityName = 5;
}

message UpdateRoad {
  message Request {
    string tripId = 1;
    repeated RoadInfo roads = 2;
    int64 entryTime = 3;
  }
  message Response { int64 entryTime = 1; }
}
