// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: trip.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude         float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude         float64 `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	AltitudeAccuracy float64 `protobuf:"fixed64,4,opt,name=altitudeAccuracy,proto3" json:"altitudeAccuracy,omitempty"`
	Accuracy         float64 `protobuf:"fixed64,5,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Heading          float64 `protobuf:"fixed64,6,opt,name=heading,proto3" json:"heading,omitempty"`
	Speed            float64 `protobuf:"fixed64,7,opt,name=speed,proto3" json:"speed,omitempty"`
	Timestamp        int64   `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 本地用
	Distance float64 `protobuf:"fixed64,9,opt,name=distance,proto3" json:"distance,omitempty"`
}

func (x *TripPosition) Reset() {
	*x = TripPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripPosition) ProtoMessage() {}

func (x *TripPosition) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripPosition.ProtoReflect.Descriptor instead.
func (*TripPosition) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{0}
}

func (x *TripPosition) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TripPosition) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TripPosition) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *TripPosition) GetAltitudeAccuracy() float64 {
	if x != nil {
		return x.AltitudeAccuracy
	}
	return 0
}

func (x *TripPosition) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *TripPosition) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *TripPosition) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *TripPosition) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TripPosition) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type TripStatistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distance     float64 `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	MaxSpeed     float64 `protobuf:"fixed64,2,opt,name=maxSpeed,proto3" json:"maxSpeed,omitempty"`
	AverageSpeed float64 `protobuf:"fixed64,3,opt,name=averageSpeed,proto3" json:"averageSpeed,omitempty"`
	MaxAltitude  float64 `protobuf:"fixed64,4,opt,name=maxAltitude,proto3" json:"maxAltitude,omitempty"`
}

func (x *TripStatistics) Reset() {
	*x = TripStatistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripStatistics) ProtoMessage() {}

func (x *TripStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripStatistics.ProtoReflect.Descriptor instead.
func (*TripStatistics) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{1}
}

func (x *TripStatistics) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *TripStatistics) GetMaxSpeed() float64 {
	if x != nil {
		return x.MaxSpeed
	}
	return 0
}

func (x *TripStatistics) GetAverageSpeed() float64 {
	if x != nil {
		return x.AverageSpeed
	}
	return 0
}

func (x *TripStatistics) GetMaxAltitude() float64 {
	if x != nil {
		return x.MaxAltitude
	}
	return 0
}

type TripPermissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShareKey string `protobuf:"bytes,1,opt,name=shareKey,proto3" json:"shareKey,omitempty"`
}

func (x *TripPermissions) Reset() {
	*x = TripPermissions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripPermissions) ProtoMessage() {}

func (x *TripPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripPermissions.ProtoReflect.Descriptor instead.
func (*TripPermissions) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{2}
}

func (x *TripPermissions) GetShareKey() string {
	if x != nil {
		return x.ShareKey
	}
	return ""
}

type Trip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 非必填
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Running、Bike、Drive
	Type        string           `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	AuthorId    string           `protobuf:"bytes,9,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Positions   []*TripPosition  `protobuf:"bytes,4,rep,name=positions,proto3" json:"positions,omitempty"`
	Statistics  *TripStatistics  `protobuf:"bytes,5,opt,name=statistics,proto3" json:"statistics,omitempty"`
	Permissions *TripPermissions `protobuf:"bytes,11,opt,name=permissions,proto3" json:"permissions,omitempty"`
	// 1 normal 0 ing -1 delete
	Status     int64 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime int64 `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime,omitempty"`
	StartTime  int64 `protobuf:"varint,10,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime    int64 `protobuf:"varint,8,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *Trip) Reset() {
	*x = Trip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trip) ProtoMessage() {}

func (x *Trip) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trip.ProtoReflect.Descriptor instead.
func (*Trip) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{3}
}

func (x *Trip) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trip) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Trip) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Trip) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Trip) GetPositions() []*TripPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *Trip) GetStatistics() *TripStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *Trip) GetPermissions() *TripPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Trip) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Trip) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Trip) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Trip) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type AddTrip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddTrip) Reset() {
	*x = AddTrip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTrip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrip) ProtoMessage() {}

func (x *AddTrip) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrip.ProtoReflect.Descriptor instead.
func (*AddTrip) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{4}
}

// 30s 更 新一次
type UpdateTripPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTripPosition) Reset() {
	*x = UpdateTripPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTripPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTripPosition) ProtoMessage() {}

func (x *UpdateTripPosition) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTripPosition.ProtoReflect.Descriptor instead.
func (*UpdateTripPosition) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{5}
}

type FinishTrip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishTrip) Reset() {
	*x = FinishTrip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishTrip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTrip) ProtoMessage() {}

func (x *FinishTrip) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTrip.ProtoReflect.Descriptor instead.
func (*FinishTrip) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{6}
}

type UpdateTrip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTrip) Reset() {
	*x = UpdateTrip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTrip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrip) ProtoMessage() {}

func (x *UpdateTrip) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrip.ProtoReflect.Descriptor instead.
func (*UpdateTrip) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{7}
}

type DeleteTrip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTrip) Reset() {
	*x = DeleteTrip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTrip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrip) ProtoMessage() {}

func (x *DeleteTrip) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrip.ProtoReflect.Descriptor instead.
func (*DeleteTrip) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{8}
}

type GetTrip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTrip) Reset() {
	*x = GetTrip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrip) ProtoMessage() {}

func (x *GetTrip) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrip.ProtoReflect.Descriptor instead.
func (*GetTrip) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{9}
}

type GetTrips struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTrips) Reset() {
	*x = GetTrips{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrips) ProtoMessage() {}

func (x *GetTrips) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrips.ProtoReflect.Descriptor instead.
func (*GetTrips) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{10}
}

type GetTripStatistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTripStatistics) Reset() {
	*x = GetTripStatistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTripStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripStatistics) ProtoMessage() {}

func (x *GetTripStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripStatistics.ProtoReflect.Descriptor instead.
func (*GetTripStatistics) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{11}
}

type AddTrip_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Running、Bike、Drive
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *AddTrip_Request) Reset() {
	*x = AddTrip_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTrip_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrip_Request) ProtoMessage() {}

func (x *AddTrip_Request) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrip_Request.ProtoReflect.Descriptor instead.
func (*AddTrip_Request) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{4, 0}
}

func (x *AddTrip_Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AddTrip_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trip *Trip `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
}

func (x *AddTrip_Response) Reset() {
	*x = AddTrip_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTrip_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrip_Response) ProtoMessage() {}

func (x *AddTrip_Response) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrip_Response.ProtoReflect.Descriptor instead.
func (*AddTrip_Response) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{4, 1}
}

func (x *AddTrip_Response) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

type UpdateTripPosition_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 必填
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 这段时间内的
	Positions []*TripPosition `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
}

func (x *UpdateTripPosition_Request) Reset() {
	*x = UpdateTripPosition_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTripPosition_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTripPosition_Request) ProtoMessage() {}

func (x *UpdateTripPosition_Request) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTripPosition_Request.ProtoReflect.Descriptor instead.
func (*UpdateTripPosition_Request) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{5, 0}
}

func (x *UpdateTripPosition_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTripPosition_Request) GetPositions() []*TripPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

type UpdateTripPosition_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTripPosition_Response) Reset() {
	*x = UpdateTripPosition_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTripPosition_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTripPosition_Response) ProtoMessage() {}

func (x *UpdateTripPosition_Response) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTripPosition_Response.ProtoReflect.Descriptor instead.
func (*UpdateTripPosition_Response) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{5, 1}
}

type FinishTrip_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 必填
	Id         string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Statistics *TripStatistics `protobuf:"bytes,3,opt,name=statistics,proto3" json:"statistics,omitempty"`
}

func (x *FinishTrip_Request) Reset() {
	*x = FinishTrip_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishTrip_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTrip_Request) ProtoMessage() {}

func (x *FinishTrip_Request) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTrip_Request.ProtoReflect.Descriptor instead.
func (*FinishTrip_Request) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{6, 0}
}

func (x *FinishTrip_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FinishTrip_Request) GetStatistics() *TripStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type FinishTrip_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *FinishTrip_Response) Reset() {
	*x = FinishTrip_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishTrip_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTrip_Response) ProtoMessage() {}

func (x *FinishTrip_Response) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTrip_Response.ProtoReflect.Descriptor instead.
func (*FinishTrip_Response) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{6, 1}
}

func (x *FinishTrip_Response) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type UpdateTrip_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 必填
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 可填，为true则是生成一个key
	ShareKey bool `protobuf:"varint,2,opt,name=shareKey,proto3" json:"shareKey,omitempty"`
	// 可填
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateTrip_Request) Reset() {
	*x = UpdateTrip_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTrip_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrip_Request) ProtoMessage() {}

func (x *UpdateTrip_Request) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrip_Request.ProtoReflect.Descriptor instead.
func (*UpdateTrip_Request) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{7, 0}
}

func (x *UpdateTrip_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTrip_Request) GetShareKey() bool {
	if x != nil {
		return x.ShareKey
	}
	return false
}

func (x *UpdateTrip_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateTrip_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 可填
	ShareKey string `protobuf:"bytes,1,opt,name=shareKey,proto3" json:"shareKey,omitempty"`
	// 可填
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateTrip_Response) Reset() {
	*x = UpdateTrip_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTrip_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrip_Response) ProtoMessage() {}

func (x *UpdateTrip_Response) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrip_Response.ProtoReflect.Descriptor instead.
func (*UpdateTrip_Response) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{7, 1}
}

func (x *UpdateTrip_Response) GetShareKey() string {
	if x != nil {
		return x.ShareKey
	}
	return ""
}

func (x *UpdateTrip_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTrip_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 必填
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTrip_Request) Reset() {
	*x = DeleteTrip_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTrip_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrip_Request) ProtoMessage() {}

func (x *DeleteTrip_Request) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrip_Request.ProtoReflect.Descriptor instead.
func (*DeleteTrip_Request) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{8, 0}
}

func (x *DeleteTrip_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTrip_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTrip_Response) Reset() {
	*x = DeleteTrip_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTrip_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrip_Response) ProtoMessage() {}

func (x *DeleteTrip_Response) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrip_Response.ProtoReflect.Descriptor instead.
func (*DeleteTrip_Response) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{8, 1}
}

type GetTrip_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 可填 传了则视为分享权限，可无视用户校验
	ShareKey string `protobuf:"bytes,2,opt,name=shareKey,proto3" json:"shareKey,omitempty"`
}

func (x *GetTrip_Request) Reset() {
	*x = GetTrip_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrip_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrip_Request) ProtoMessage() {}

func (x *GetTrip_Request) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrip_Request.ProtoReflect.Descriptor instead.
func (*GetTrip_Request) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetTrip_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTrip_Request) GetShareKey() string {
	if x != nil {
		return x.ShareKey
	}
	return ""
}

type GetTrip_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trip *Trip `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
}

func (x *GetTrip_Response) Reset() {
	*x = GetTrip_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrip_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrip_Response) ProtoMessage() {}

func (x *GetTrip_Response) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrip_Response.ProtoReflect.Descriptor instead.
func (*GetTrip_Response) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{9, 1}
}

func (x *GetTrip_Response) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

type GetTrips_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 可选
	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	// 必选 All、Running、Bike、Drive
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// 可选 [createTime,endTime]
	TimeLimit []int64 `protobuf:"varint,3,rep,packed,name=timeLimit,proto3" json:"timeLimit,omitempty"`
	// 可选 CreateTime / TotalDistance，默认 CreateTime
	Sort     string `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	PageNum  int64  `protobuf:"varint,5,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize int64  `protobuf:"varint,6,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *GetTrips_Request) Reset() {
	*x = GetTrips_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrips_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrips_Request) ProtoMessage() {}

func (x *GetTrips_Request) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrips_Request.ProtoReflect.Descriptor instead.
func (*GetTrips_Request) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{10, 0}
}

func (x *GetTrips_Request) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetTrips_Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetTrips_Request) GetTimeLimit() []int64 {
	if x != nil {
		return x.TimeLimit
	}
	return nil
}

func (x *GetTrips_Request) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetTrips_Request) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetTrips_Request) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetTrips_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*Trip `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetTrips_Response) Reset() {
	*x = GetTrips_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrips_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrips_Response) ProtoMessage() {}

func (x *GetTrips_Response) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrips_Response.ProtoReflect.Descriptor instead.
func (*GetTrips_Response) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{10, 1}
}

func (x *GetTrips_Response) GetList() []*Trip {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetTrips_Response) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetTripStatistics_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 可选
	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	// 必选 Running、Bike、Drive
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// 可选 [createTime,endTime]
	TimeLimit []int64 `protobuf:"varint,3,rep,packed,name=timeLimit,proto3" json:"timeLimit,omitempty"` // 可选 CreateTime / TotalDistance，默认 CreateTime
}

func (x *GetTripStatistics_Request) Reset() {
	*x = GetTripStatistics_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTripStatistics_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripStatistics_Request) ProtoMessage() {}

func (x *GetTripStatistics_Request) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripStatistics_Request.ProtoReflect.Descriptor instead.
func (*GetTripStatistics_Request) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GetTripStatistics_Request) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetTripStatistics_Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetTripStatistics_Request) GetTimeLimit() []int64 {
	if x != nil {
		return x.TimeLimit
	}
	return nil
}

type GetTripStatistics_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// s
	Time int64 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	// m
	Distance float64 `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
	List     []*Trip `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetTripStatistics_Response) Reset() {
	*x = GetTripStatistics_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trip_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTripStatistics_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripStatistics_Response) ProtoMessage() {}

func (x *GetTripStatistics_Response) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripStatistics_Response.ProtoReflect.Descriptor instead.
func (*GetTripStatistics_Response) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{11, 1}
}

func (x *GetTripStatistics_Response) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetTripStatistics_Response) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *GetTripStatistics_Response) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *GetTripStatistics_Response) GetList() []*Trip {
	if x != nil {
		return x.List
	}
	return nil
}

var File_trip_proto protoreflect.FileDescriptor

var file_trip_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x72, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x72,
	0x69, 0x70, 0x22, 0x96, 0x02, 0x0a, 0x0c, 0x54, 0x72, 0x69, 0x70, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x61, 0x6c, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x41, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x10, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x41, 0x63, 0x63,
	0x75, 0x72, 0x61, 0x63, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x70, 0x65, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x0e,
	0x54, 0x72, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61,
	0x78, 0x53, 0x70, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6d, 0x61,
	0x78, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x53, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x61, 0x76,
	0x65, 0x72, 0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61,
	0x78, 0x41, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0b, 0x6d, 0x61, 0x78, 0x41, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x2d, 0x0a, 0x0f,
	0x54, 0x72, 0x69, 0x70, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x68, 0x61, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x68, 0x61, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x22, 0xeb, 0x02, 0x0a, 0x04,
	0x54, 0x72, 0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x72,
	0x69, 0x70, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x34, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x74, 0x72, 0x69, 0x70, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x12, 0x37, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x72, 0x69, 0x70, 0x2e, 0x54, 0x72, 0x69,
	0x70, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0b, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x54, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x54, 0x72, 0x69, 0x70, 0x1a, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x1a, 0x2a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1e, 0x0a, 0x04, 0x74, 0x72, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x74, 0x72, 0x69, 0x70, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x52, 0x04, 0x74, 0x72, 0x69, 0x70, 0x22,
	0x6d, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x69, 0x70, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x4b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x30, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x72, 0x69, 0x70, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x83,
	0x01, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x72, 0x69, 0x70, 0x1a, 0x4f, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74,
	0x72, 0x69, 0x70, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x1a, 0x24,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x72, 0x69, 0x70, 0x1a, 0x49, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x68, 0x61, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x73, 0x68, 0x61, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x3a,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x0a, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x69, 0x70, 0x1a, 0x19, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x6c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x72, 0x69, 0x70, 0x1a, 0x35, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x61, 0x72, 0x65, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x61, 0x72, 0x65, 0x4b, 0x65,
	0x79, 0x1a, 0x2a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x04, 0x74, 0x72, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x72,
	0x69, 0x70, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x52, 0x04, 0x74, 0x72, 0x69, 0x70, 0x22, 0xe4, 0x01,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x72, 0x69, 0x70, 0x73, 0x1a, 0x95, 0x01, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70,
	0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x1a, 0x40, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74,
	0x72, 0x69, 0x70, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x22, 0xd2, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x72, 0x69, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x1a, 0x4b, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x1a, 0x70, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x72, 0x69, 0x70, 0x2e, 0x54,
	0x72, 0x69, 0x70, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trip_proto_rawDescOnce sync.Once
	file_trip_proto_rawDescData = file_trip_proto_rawDesc
)

func file_trip_proto_rawDescGZIP() []byte {
	file_trip_proto_rawDescOnce.Do(func() {
		file_trip_proto_rawDescData = protoimpl.X.CompressGZIP(file_trip_proto_rawDescData)
	})
	return file_trip_proto_rawDescData
}

var file_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_trip_proto_goTypes = []interface{}{
	(*TripPosition)(nil),                // 0: trip.TripPosition
	(*TripStatistics)(nil),              // 1: trip.TripStatistics
	(*TripPermissions)(nil),             // 2: trip.TripPermissions
	(*Trip)(nil),                        // 3: trip.Trip
	(*AddTrip)(nil),                     // 4: trip.AddTrip
	(*UpdateTripPosition)(nil),          // 5: trip.UpdateTripPosition
	(*FinishTrip)(nil),                  // 6: trip.FinishTrip
	(*UpdateTrip)(nil),                  // 7: trip.UpdateTrip
	(*DeleteTrip)(nil),                  // 8: trip.DeleteTrip
	(*GetTrip)(nil),                     // 9: trip.GetTrip
	(*GetTrips)(nil),                    // 10: trip.GetTrips
	(*GetTripStatistics)(nil),           // 11: trip.GetTripStatistics
	(*AddTrip_Request)(nil),             // 12: trip.AddTrip.Request
	(*AddTrip_Response)(nil),            // 13: trip.AddTrip.Response
	(*UpdateTripPosition_Request)(nil),  // 14: trip.UpdateTripPosition.Request
	(*UpdateTripPosition_Response)(nil), // 15: trip.UpdateTripPosition.Response
	(*FinishTrip_Request)(nil),          // 16: trip.FinishTrip.Request
	(*FinishTrip_Response)(nil),         // 17: trip.FinishTrip.Response
	(*UpdateTrip_Request)(nil),          // 18: trip.UpdateTrip.Request
	(*UpdateTrip_Response)(nil),         // 19: trip.UpdateTrip.Response
	(*DeleteTrip_Request)(nil),          // 20: trip.DeleteTrip.Request
	(*DeleteTrip_Response)(nil),         // 21: trip.DeleteTrip.Response
	(*GetTrip_Request)(nil),             // 22: trip.GetTrip.Request
	(*GetTrip_Response)(nil),            // 23: trip.GetTrip.Response
	(*GetTrips_Request)(nil),            // 24: trip.GetTrips.Request
	(*GetTrips_Response)(nil),           // 25: trip.GetTrips.Response
	(*GetTripStatistics_Request)(nil),   // 26: trip.GetTripStatistics.Request
	(*GetTripStatistics_Response)(nil),  // 27: trip.GetTripStatistics.Response
}
var file_trip_proto_depIdxs = []int32{
	0, // 0: trip.Trip.positions:type_name -> trip.TripPosition
	1, // 1: trip.Trip.statistics:type_name -> trip.TripStatistics
	2, // 2: trip.Trip.permissions:type_name -> trip.TripPermissions
	3, // 3: trip.AddTrip.Response.trip:type_name -> trip.Trip
	0, // 4: trip.UpdateTripPosition.Request.positions:type_name -> trip.TripPosition
	1, // 5: trip.FinishTrip.Request.statistics:type_name -> trip.TripStatistics
	3, // 6: trip.GetTrip.Response.trip:type_name -> trip.Trip
	3, // 7: trip.GetTrips.Response.list:type_name -> trip.Trip
	3, // 8: trip.GetTripStatistics.Response.list:type_name -> trip.Trip
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_trip_proto_init() }
func file_trip_proto_init() {
	if File_trip_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trip_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripStatistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripPermissions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTrip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTripPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishTrip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTrip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTrip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrips); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTripStatistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTrip_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTrip_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTripPosition_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTripPosition_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishTrip_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishTrip_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTrip_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTrip_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTrip_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTrip_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrip_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrip_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrips_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrips_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTripStatistics_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trip_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTripStatistics_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trip_proto_goTypes,
		DependencyIndexes: file_trip_proto_depIdxs,
		MessageInfos:      file_trip_proto_msgTypes,
	}.Build()
	File_trip_proto = out.File
	file_trip_proto_rawDesc = nil
	file_trip_proto_goTypes = nil
	file_trip_proto_depIdxs = nil
}
